### ISSUE TITLE
script contract solver not accepting an empty string solutions

### ISSUE THREAD

**Issue by EvGym** [danielyxie/bitburner#3573]
When trying to solve the shortest path in a grid contract, a script will be unable to solve it if there is no path. I have tried returning the following: [], [""], '', "", null, and undefined\

All of these resulted in the contract failing. I have backed up that save in case it is needed and then tried solving it just by entering in nothing and it solved. 

Grid:
[0,0,1,0,0,0,1],
[1,0,0,0,0,1,0],
[0,0,0,0,1,0,0],
[0,1,0,0,1,0,1],
[0,0,1,0,0,0,1],
[1,1,0,0,1,1,0],
[1,1,1,1,0,0,0],
[0,0,1,1,1,0,0],
[0,1,0,0,0,1,0]

contract-275797.cct

**Comment by EvGym** [comment]
This seems to expand to even the array jumping game as solutions needing a 0 response also fail. I also set aside a save for that

**Comment by EvGym** [comment]
This also occurs with Find All Valid Math Expressions.

This may be global with all solutions that aren't either "yes" or "these are the solutions"

**Comment by phyzical** [comment]
OH so you typed "" into the contract solving modal? 

the thing is "" is correct for the api usage, if you were to type `""` into the modal your answer actually becomes `'""'`

Maybe we can detect `""` entered into the modal and just make it equal an empty string to avoid this confusion going forward

**Comment by EvGym** [comment]
No, when I say "" I mean I did this:
```
solution = ""
ns.codingcontract.attempt(solution, contract, server, [true])
```

and it still failed despite me just pressing the solve button being the answer.

Sorry if I didn't make that clear.

That being said, that is a good idea. I am sure people have also tried returning `"''"` since in the example it has said the solution for grids with no path is `''`

**Comment by phyzical** [comment]
hmm and to confirm your saying that solution without setting anything ended up solving it? code wise the snipper you provided should have been resolved as the correct answer

**Comment by EvGym** [comment]
In the example I provided, just pressing the submit button solved the contract.
In the same example above, submitting an empty string as the solution via a program failed to solve the contract

I found similar problems occurred with "Array Jumpinh Game II" when trying to submit 0 and "Find all Valid Math Expressions" when submitting 0

**Comment by dowinter** [comment]
I also observed the same problem, my puzzle was the following:
```
[04:41:17] rls.js: The-Cave -> ["contract-769474-Sector-12.cct<Shortest Path in a Grid>[[0,0,0,1,0,0,0,0,0],[0,0,1,1,0,0,1,1,0],[0,0,0,0,0,0,0,1,0],[0,0,0,0,0,0,0,1,0],[0,0,1,0,0,1,0,1,0],[0,0,0,0,0,0,1,0,0],[0,1,0,1,0,0,0,0,0]]"]

[04:41:17] /contracts/solve.js: Submitting solution <> to contract of The-Cave
```
Notice that `<>` means an empty string, i just wrap it in brackets for the log. It doesn't get accepted via API though, while the manual dialog works.

**Comment by phyzical** [comment]
yeah i had a scan of the code and i couldn't see any reason why an empty string wouldn't be letting it through, it may be the `helper.string` does something to an empty string and silently fails? can either of you confirm if there was any logs output around the puzzle being incorrect or did it just output nothing?

**Comment by EvGym** [comment]
Where do we get the logs for it?

I am still seeing this bug almost on a daily basis. Every time 0 or an empty string is expected

**Comment by Iriel** [comment]
For this particular challenge it seems (from one test, since I can't force challenges to appear on-demand)that the API accepts `"[]"`  (A string containing an open and close bracket) but not `[]` (an empty array).

**Comment by ethall** [comment]
If you're using the TypeScript API and wanting to adhere to the declared function signature for `ns.codingcontract.attempt`, then the "Proper 2-Coloring of a Graph" also accepts `["[]"]` as an `answer` argument.
